name: todos CI

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]

jobs:
    init:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [17.x]
        steps:
            - uses: actions/checkout@v4
            - name: Starting Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run build:prod
            - run: npm run unit
            - run: npm run lint:ci
